services:
  mysql:
    image: mysql:8.4
    container_name: mysql

    environment:
      TZ: Asia/Kolkata
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3307:3306" # to avoid local mysql collision

    volumes:
      - mysql_data:/var/lib/mysql
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  cli-app:
    container_name: cli-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      TZ: Asia/Kolkata
      DB_HOST: mysql          # service name, not localhost
      DB_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TOTP_ISSUER: ${TOTP_ISSUER}
      SESSION_TIMEOUT_MINUTES: ${SESSION_TIMEOUT_MINUTES:-15}
    
    volumes:
      - clilogin_data:/root/.clilogin # to store the jwt token that was created, so it persist across container re-builds and restarts

    stdin_open: true   # keep STDIN open, required for interactive input
    tty: true          # allocate a pseudo-TTY, required for readline to work correctly

volumes:
  mysql_data:
  clilogin_data: